In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

arr_2d = arr.reshape(2, 3)
print("1D to 2D Array:")
print(arr_2d)

print("\nArray Attributes:")
print("Shape:", arr_2d.shape)
print("Dimensions:", arr_2d.ndim)
print("Data Type:", arr_2d.dtype)
print("Item Size:", arr_2d.itemsize)

arr_9 = np.full((3, 3), 9)
print("\n3x3 Array of 9:")
print(arr_9)

even_space = np.linspace(25, 125, 10)
print("\n10 Evenly Spaced Values:")
print(even_space)

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
print("\nPython List to NumPy Array:")
print(np_array)

reverse_arr = np_array[::-1]
print("\nReversed Array:")
print(reverse_arr)

arr_3d = np.arange(1, 49).reshape(4, 4, 3)
print("\n4x4x3 Array:")
print(arr_3d)

print("\nSecond Set, First Row, Last Column:")
print(arr_3d[1, 0, 2])

arr_4x4 = np.arange(1, 17).reshape(4, 4)
print("\n4x4 Array:")
print(arr_4x4)

print("\nOdd Rows and Even Columns:")
print(arr_4x4[::2, 1::2])

print("\nFirst Two Rows and First Two Columns of Second Set:")
print(arr_3d[1, :2, :2])

arr_replace = np.array([[23, 56, 78, 93],
                        [71, 82, 13, 24]])

for i in range(arr_replace.shape[0]):
    for j in range(arr_replace.shape[1]):
        if arr_replace[i, j] % 2 != 0:
            arr_replace[i, j] = -1

print("\nOdd Numbers Replaced with -1:")
print(arr_replace)

arr_nonzero = np.array([1, 0, 2, 0, 3, 0, 4])

print("\nIndices of Non-Zero Elements:")
print(np.nonzero(arr_nonzero))

arr1 = np.array([10, 20, 30])
arr2 = np.array([5, 10, 15])

print("\nAddition:")
print(arr1 + arr2)

print("\nMultiplication:")
print(arr1 * arr2)

arr3 = np.array([15, 20, 25])
arr4 = np.array([10, 40, 37])

dot_product = np.dot(arr3, arr4)

print("\nDot Product:")
print(dot_product)

1D to 2D Array:
[[10 20 30]
 [40 50 60]]

Array Attributes:
Shape: (2, 3)
Dimensions: 2
Data Type: int64
Item Size: 8

3x3 Array of 9:
[[9 9 9]
 [9 9 9]
 [9 9 9]]

10 Evenly Spaced Values:
[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]

Python List to NumPy Array:
[1 2 3 4 5]

Reversed Array:
[5 4 3 2 1]

4x4x3 Array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]

Second Set, First Row, Last Column:
15

4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Odd Rows and Even Columns:
[[ 2  4]
 [10 12]]

First Two Rows and First Two Columns of Second Set:
[[13 14]
 [16 17]]

Odd Numbers Replaced with -1:
[[-1 56 78 -1]
 [-1 82 -1 24]]

Indices of Non-Zero Elements:
(array([0, 2, 4, 6]),)

Addition:
[15 30 45]

Multipl