In [1]:
import numpy as np

arr = np.array([[6, -8, 73, -110],
                [np.nan, -8, 0, 94]])

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

# Interchange rows and columns (transpose)
result = arr.T

print(result)

[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [2]:
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)

# Move axis 0 to position 2
result = np.moveaxis(arr, 0, 2)

print(result.shape)
print(result)

(3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]


In [3]:
import numpy as np

arr = np.array([[1, np.nan, 3],
                [4, 5, np.nan],
                [7, 8, 9]])

col_mean = np.nanmean(arr, axis=0)

inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])

print(arr)

[[1.  6.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [4]:
import numpy as np

arr = np.array([6, -8, 73, -110, 42])

arr[arr < 0] = 0

print(arr)

[ 6  0 73  0 42]
