In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])

combined = np.vstack((arr1, arr2))

print("Combined Array:")
print(combined)

Combined Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flattened = arr.flatten()

print("Flattened Array:")
print(flattened)

Flattened Array:
[1 2 3 4 5 6]


In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

reversed_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array:", reversed_arr)

Original Array: [10 20 30 40 50]
Reversed Array: [50 40 30 20 10]


In [4]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Array:")
print(arr)

print("\nMaximum Value:")
print(np.max(arr))

print("\nMinimum Value:")
print(np.min(arr))

rows, columns = arr.shape
print("\nRows:", rows)
print("Columns:", columns)

print("\nAll Elements:")
for row in arr:
    for element in row:
        print(element, end=" ")

print("\n\nSpecific Element:")
print(arr[1, 2])

sum_value = 0
for row in arr:
    for element in row:
        sum_value += element

print("\nSum of Elements:")
print(sum_value)

arr1 = np.array([10, 20, 30])
arr2 = np.array([5, 10, 15])

print("\nAddition:")
print(arr1 + arr2)

print("\nSubtraction:")
print(arr1 - arr2)

print("\nMultiplication:")
print(arr1 * arr2)

print("\nDivision:")
print(arr1 / arr2)

Array:
[[10 20 30]
 [40 50 60]]

Maximum Value:
60

Minimum Value:
10

Rows: 2
Columns: 3

All Elements:
10 20 30 40 50 60 

Specific Element:
60

Sum of Elements:
210

Addition:
[15 30 45]

Subtraction:
[ 5 10 15]

Multiplication:
[ 50 200 450]

Division:
[2. 2. 2.]


In [5]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Array:")
print(arr)

print("\nMaximum Value:")
print(np.max(arr))

print("\nMinimum Value:")
print(np.min(arr))

rows, columns = arr.shape
print("\nRows:", rows)
print("Columns:", columns)

print("\nAll Elements:")
for row in arr:
    for element in row:
        print(element, end=" ")

print("\n\nSpecific Element:")
print(arr[1, 2])

sum_value = 0
for row in arr:
    for element in row:
        sum_value += element

print("\nSum of Elements:")
print(sum_value)

arr1 = np.array([10, 20, 30])
arr2 = np.array([5, 10, 15])

print("\nAddition:")
print(arr1 + arr2)

print("\nSubtraction:")
print(arr1 - arr2)

print("\nMultiplication:")
print(arr1 * arr2)

print("\nDivision:")
print(arr1 / arr2)

Array:
[[10 20 30]
 [40 50 60]]

Maximum Value:
60

Minimum Value:
10

Rows: 2
Columns: 3

All Elements:
10 20 30 40 50 60 

Specific Element:
60

Sum of Elements:
210

Addition:
[15 30 45]

Subtraction:
[ 5 10 15]

Multiplication:
[ 50 200 450]

Division:
[2. 2. 2.]


In [9]:
import numpy as np


arr1 = np.array([[10, 20, 30],
                 [40, 50, 60]])

arr2 = np.array([[15, 25, 35],
                 [45, 55, 65]])

average = (arr1 + arr2) / 2

print("Average of Arrays:")
print(average)

combined = np.concatenate((arr1.flatten(), arr2.flatten()))

print("\nMean:")
print(np.mean(combined))

print("\nMedian:")
print(np.median(combined))



Average of Arrays:
[[12.5 22.5 32.5]
 [42.5 52.5 62.5]]

Mean:
37.5

Median:
37.5
